### ISSUE TITLE
remainders in database

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#18]
It is a small issue, but I noticed that - although Prestashop modules such as statistics are deleted from the server they are not deleted from the database.

**Comment by Traumflug** [comment]
Thanks for reporting.

These statistics modules got replaced by one new statistics module (*statsmodule*), which should cover functionality of all the ~20 previous statistics modules, and use all these tables accordingly. Does this explain the observed behavior?

**Comment by musicpanda** [comment]
What I mean is that there are staying remains in the database. And you can see them also in Positions.
![missing](https://user-images.githubusercontent.com/13930107/51077471-9ebc4980-16a7-11e9-8c3b-b777595d8225.jpg)
![phpadmin](https://user-images.githubusercontent.com/13930107/51077474-a2e86700-16a7-11e9-8b3f-be045d4d5a3b.jpg)
![positions](https://user-images.githubusercontent.com/13930107/51077476-a54ac100-16a7-11e9-9a14-d7f26a8f8d1f.jpg)

**Comment by Traumflug** [comment]
I see. It's about the flag for the module its self in the `ps_modules` table.

This should get solved [here](https://github.com/thirtybees/psonesixmigrator/blob/master/classes/AjaxProcessor.php#L865) and [here](https://github.com/thirtybees/psonesixmigrator/blob/master/classes/AjaxProcessor.php#L1587-L1621). Uninstallation of these modules (rather than just deleting module files on disk) was introduced with the latest version, so please make sure you use [version 2.0.0](https://github.com/thirtybees/psonesixmigrator/releases/tag/2.0.0).

If you do use 2.0.0, PS apparently doesn't uninstall these modules properly, requiring a workaround.

**Comment by Traumflug** [comment]
Just verified this with a fresh migration of a realworld shop (and version 2.0.0). Statistics modules were removed automatically, including entries in table *PREFIX_module*.

Assuming this was fixed with the newer module version. In case it happens again, please don't hesitate to file a new issue or reopen this one.
