### ISSUE TITLE
"An upgrade is available" mysteries

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#9]
After the migration the modules page of the backoffice shows a long list of modules that should be upgraded:
![thirty9](https://user-images.githubusercontent.com/13930107/30786485-bd0f17fc-a176-11e7-9369-18f45cd91db1.jpg)

This list remains after updating to 1.03. 

I tried to click on "update all" under 1.03, but nothing seemed to happen. Then I decided to click on one of those listed modules to force that one to upgrade. I am not sure which one I clicked. Anyway, I immediately arrived on an error page:
![thirty6](https://user-images.githubusercontent.com/13930107/30786504-3f7b0dc2-a177-11e7-896a-d54645d1c09b.jpg)

The only way out was to rename the cron module. After I did that I got back on the modules page where I saw the message that the Paypal module had been updated. This certainly wasn't the name I had clicked...

I am not sure what happened here, but it didn't feel right.

**Comment by Traumflug** [comment]
Well, this long list of modules to update is expected. Not only because most modules received improvements, but also because they're thirty bees modules after the migration.

The error hints to a broken *cronjob* module, it can only get fixed there.

As this report is quite old, isn't related to the migration module (module updates happen elsewhere) and I never experienced such flaws during all the shop migrations I did, I'm going to close this. In case this problem appears again, please don't hesitate to open another report, or re-open this one.
